### ISSUE TITLE
JSON candidates are reduced to zero bytes, causing crash

### ISSUE THREAD

**Issue by wolfgang42** [wala/jsdelta#25]
To reproduce:
```bash
echo '{"foo": 3}' > test.json
jsdelta --cmd false test.json
```

Result:
```
Testing candidate /tmp/tmp1/delta_js_0.json (11 bytes)
    aborted with error
Starting iteration #0
Target: /tmp/tmp1/delta_js_1.json (1 bytes)
Testing candidate /tmp/tmp1/delta_js_1.json (1 bytes)
    aborted with error
Starting iteration #1

/usr/lib/node_modules/jsdelta/src/file_util.js:43
        throw e;
        ^
Error: Line 2: Unexpected end of input
    at constructError (/usr/lib/node_modules/jsdelta/node_modules/esprima/esprima.js:2406:21)
    at createError (/usr/lib/node_modules/jsdelta/node_modules/esprima/esprima.js:2425:17)
    at unexpectedTokenError (/usr/lib/node_modules/jsdelta/node_modules/esprima/esprima.js:2499:13)
    at throwUnexpectedToken (/usr/lib/node_modules/jsdelta/node_modules/esprima/esprima.js:2504:15)
    at expect (/usr/lib/node_modules/jsdelta/node_modules/esprima/esprima.js:2522:13)
    at parseGroupExpression (/usr/lib/node_modules/jsdelta/node_modules/esprima/esprima.js:3138:17)
    at inheritCoverGrammar (/usr/lib/node_modules/jsdelta/node_modules/esprima/esprima.js:2680:18)
    at parsePrimaryExpression (/usr/lib/node_modules/jsdelta/node_modules/esprima/esprima.js:3238:20)
    at inheritCoverGrammar (/usr/lib/node_modules/jsdelta/node_modules/esprima/esprima.js:2680:18)
    at parseLeftHandSideExpressionAllowCall (/usr/lib/node_modules/jsdelta/node_modules/esprima/esprima.js:3413:20)
```

`delta_js_1.json` consists of a single newline; I assume what's going on here is that the JSON is being reduced down to what would be a syntactically valid JavaScript program (which does nothing at all) and then interpreted as JSON (which doesn't like an empty string).

**Comment by msridhar** [comment]
Yup that's a bug. @esbena do you have time to take a look?

**Comment by esbena** [comment]
@wolfgang42 : 
>  I assume what's going on here is that the JSON is being reduced down to what would be a syntactically valid JavaScript program

That is exactly what was wrong.
